dist: xenial

language: go
go: "1.14.x"

git:
  submodules: false

branches:
  only:
    - master

_integration_test: &integration_test
  os: linux
  language: minimal
  before_install: ./check-skip-integration.sh

jobs:
  include:
    - name: "test"
      <<: *integration_test
      script:
        - echo Running test
