dist: xenial

language: go
go: "1.14.x"

git:
  submodules: false

branches:
  only:
    - master

_integration_test: &integration_test
  os: linux
  language: minimal
  before_install:
    - echo running pretest
    #Skip integration tests if changes are only in the `docs` directory. This only works for a pull-request based development workflow like X's. 
    - git diff --name-only "$TRAVIS_BRANCH"... | grep -v '^docs/' || travis_terminate 0


jobs:
  include:
    - name: "test"
      <<: *integration_test
      script:
        - echo Running test
