dist: xenial

language: go
go: "1.14.x"

git:
  submodules: false

branches:
  only:
    - master

_integration_test: &integration_test
  os: linux
  language: minimal
  before_install:
    - echo running pretest
    - if [ -z "$(git diff --name-only "$TRAVIS_BRANCH"...HEAD | grep -v '^foo/')" ]; then echo Skipping integration tests && travis_terminate 0 fi

jobs:
  include:
    - name: "test"
      <<: *integration_test
      script:
        - echo Running test
